### ISSUE TITLE
상품 데이터 렌더링

### ISSUE THREAD

**Issue by choisohyun** [codesquad-memeber-2020/vm-2#6]
- [x] 상품 리스트 innerHTML로 렌더링하기

**Comment by crongro** [comment]
view 라벨은 js도 아니고 css인가요?  아니면 그냥 UI쪽 모두?
애매해보이는데 정의가 궁금하네요.

**Comment by choisohyun** [comment]
> view 라벨은 js도 아니고 css인가요? 아니면 그냥 UI쪽 모두?
> 애매해보이는데 정의가 궁금하네요.

잘못 단 것 같습니다! `view => html`로 변경했습니다.

**Comment by choisohyun** [comment]
#12 완료

**Comment by wowww** [comment]
#15 상품 데이터 랜더링 wallet 가격, 개수 추가
